dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  lottie: ^3.1.3
  audioplayers: ^6.0.0
  google_fonts: ^6.2.1
  animate_do: ^3.3.4 # Great for quick entry animations